# Generated by Django 4.2.6 on 2023-10-27 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='The value must greater than 1.'), django.core.validators.MaxValueValidator(10, message='The value must smaller than 10.')]),
        ),
    ]
