# Generated by Django 4.2.6 on 2023-10-28 13:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_alter_presentationresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationresult',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='presentationresult',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_results', to='conference.conference'),
        ),
        migrations.AlterField(
            model_name='presentationresult',
            name='result',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='The value must greater than 1.'), django.core.validators.MaxValueValidator(10, message='The value must smaller than 10.')]),
        ),
        migrations.AlterField(
            model_name='presentationresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
