# Generated by Django 4.2.6 on 2023-10-28 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_alter_presentationresult_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationresult',
            name='recommended',
        ),
        migrations.RemoveField(
            model_name='presentationresult',
            name='result',
        ),
        migrations.AddField(
            model_name='conference',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='result',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, message='The value must greater than 1.'), django.core.validators.MaxValueValidator(10, message='The value must smaller than 10.')]),
        ),
    ]
